# Generated by Django 5.1.6 on 2025-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Admin approval required for account activation",
            ),
        ),
    ]
