# Generated by Django 5.1.6 on 2025-07-01 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minuites",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cb4b5c75-a38f-488b-8e64-8772c9afe031"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
