# Generated by Django 5.2.4 on 2025-07-28 19:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_minuites_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Work Programmes Graduate'",
                        max_length=200,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of display (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="financialcheckbook",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="financialcheckbook",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="financialcheckbook",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="financialcheckbook",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="financialcheckbook",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("429d0155-0456-4aee-bdf9-9443617c60e1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="minuites",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e9c3d586-ebb7-435b-929a-5c3c34db7e89"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
